version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: et-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "Manognabandi@21"
      MYSQL_DATABASE: "expense_db"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .                   # <-- root of repo
      dockerfile: Dockerfile.backend
    container_name: et-backend
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/expense_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Manognabandi@21"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: "8082"
      JWT_SECRET: "VerySecretKeyThatShouldBeReplacedWithEnvVariable1234567890"
      JWT_EXPIRATION_MS: "86400000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: .                  # <-- root of repo
      dockerfile: Dockerfile.frontend
    container_name: et-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5174:80"

volumes:
  db_data:
